- name: Find or create instances
  hosts: localhost
  tasks:
    - include_vars: vars.yml

    # the postgres role depends on the common role
    - include_role:
         name: postgres
         tasks_from: create

    - include_role:
         name: mattermost
         tasks_from: create
    
    - name: find instance ids
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Application": "mattermost"
          "tag:User": "kathrin"
      register: instance_info

    - set_fact:
         instance_ids: "{{ instance_info | community.general.json_query('instances[*].instance_id') }}"


