- name: Prepare instance for running postgres
  become: yes
  hosts: tag_database
  remote_user: root
  become_method: sudo
  tasks:
  - name: install postgres
    apt:
       pkg:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2 # community.postgres requirement
          - acl # community.postgres requirement
       state: latest
       update_cache: true

  - name: add postgres to systemd
    ansible.builtin.systemd:
       name: postgresql
       enabled: yes

  - name: create mattermost database
    community.postgresql.postgresql_db:
      name: "{{db_name}}"
      state: present
    become: yes
    become_user: postgres # for authentication user must be "postgres"

  - name: create mattermost user
    community.postgresql.postgresql_user:
      name: "{{db_username}}"
      password: "{{db_password}}"
    become_user: postgres

  - name: grant the user access to the Mattermost database
    community.postgresql.postgresql_privs:
      db: "{{db_name}}"
      privs: ALL
      roles: "{{db_username}}"
      objs: ALL_IN_SCHEMA
    become_user: postgres

  - name: ensure postgres listens on "*"
    lineinfile: #to replace a line
      dest: /etc/postgresql/14/main/postgresql.conf
      regexp: "#listen_addresses ="
      line: "listen_addresses = '*'"

  - name: obtain the private ip address of the mattermost server
    set_fact: private_ip="{{ hostvars[item].private_ip_address }}"
    with_items: "{{ groups[tag_mattermost] }}"
    register: mm_ips

  - name: set private ip fact
    set_fact: mm_private_ip="{{ mm_ips.result | map(attribute='ansible_facts.private_ip') }}"

  - debug: var=mm_private_ip


  - name: modify the file pg_hba.conf to allow the Mattermost server to communicate with the database.
    blockinfile:
      dest: /etc/postgresql/14/main/pg_hba.conf
      marker: "{mark}"
      marker_begin: '# "local" is for Unix domain socket connections only'
      marker_end: '# Allow replication connections from localhost, by a user with the'
      block: |

        local   all             all                             trust

        host    all             all         127.0.0.1/32        trust
        host    all             all         {{mm_private_ip}}/32        trust
        host    all             all         ::1/128             trust

  - name: reload postgresql service
    ansible.builtin.systemd:
       name: postgresql
       state: reloaded

- name: Prepare instance for running mattermost
  become: yes
  hosts: tag_mattermost
  remote_user: root
  become_method: sudo
  tasks:

  - name: install depencencies
    apt:
      pkg:
        - nginx
      state: latest
      update_cache: true
  
    
