- name: create mattermost instance
  amazon.aws.ec2_instance:
    name: "kathrin-mm-instance"
    state: started
    exact_count: 1
    key_name: "kathrin-mm-key-pair"
    security_groups:
    -  "kathrin-mm-security-group"
    -  "kathrin-mm-admin-group"
    filters:
      "tag:Name": "kathrin-mm-instance"
      "instance-state-name": "running"
    vpc_subnet_id : "{{ db_instance_subnet }}"
    instance_type: t2.micro
    image_id: "ami-065deacbcaac64cf2"
    detailed_monitoring: yes
    instance_role: logstreamers
    tags:
       Application: mattermost
       User: kathrin
       Purpose: mattermost

