- name: create apache instance
  amazon.aws.ec2_instance:
     name: "{{ reverseproxy_instance_name }}"
     state: started
     exact_count: 1
     key_name: "{{ name_prefix }}-mm-key-pair"
     security_groups:
     - "{{ name_prefix }}-mm-admin-group"
     filters:
        "tag:Name": "{{ reverseproxy_instance_name }}"
        "instance-state-name": "running"
     vpc_subnet_id: "{{ db_instance_subnet }}"
     instance_type: t2.micro
     image_id: "{{ loadtest_ami }}"
     detailed_monitoring: yes
     instance_role: logstreamers
     tags:
        Application: mattermost
        User: "{{ name_prefix }}"
        Purpose: "{{ reverseproxy_purpose_tag }}"

