apiVersion: v1
kind: Service
metadata:
  name: "mattermost"
spec:
  ports:
    - name: http
      port: 8065
      protocol: TCP
  selector:
    app: mattermost

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  labels:
    app: mattermost
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
      - name: mattermost
        image: "mattermost/mattermost-team-edition:7.5.2"
        env:
        - name: MM_USERNAME
          valueFrom:
            secretKeyRef:
              name: mattermost.creds
              key: USER

        - name: MM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost.creds
              key: PASSWORD

        - name: MM_DBNAME  
          valueFrom:
            secretKeyRef:
              name: mattermost.creds
              key: DATABASE

        - name: MM_SQLSETTINGS_DATASOURCE
          valueFrom:
            secretKeyRef:
              name: mattermost.creds
              key: SQL_SETTINGS
          
        - name: MM_SQLSETTINGS_DRIVERNAME
          value: "postgres"
        ports:
        - containerPort: 8065
          name: http
        volumeMounts:
        # optional persistent storage
        #- name: appdata
          #mountPath: /mattermost/data
        - name: etclocaltime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      # optional persistent storage
      #- name: appdata
        #persistentVolumeClaim:
        #  claimName: mattermost-app
      - name: etclocaltime
        hostPath:
          path: /etc/localtime