---
- name: Update Ec2 instance
  become: yes
  hosts: mattermost
  remote_user: root
  become_method: sudo
  tasks:

  - name: install depencences
    apt:
      pkg:
        - nginx
        - postgresql
        - postgresql-contrib
      state: latest
      update_cache: true
  
  - name: start nginx
    service:
      name: nginx
      state: started

  - name: enable nginx service
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      masked: no
  
  - name: get the mattermost package
    become: yes
    unarchive:
      src: https://releases.mattermost.com/7.1.2/mattermost-7.1.2-linux-amd64.tar.gz
      dest: /opt
      remote_src: true
      validate_certs: yes

  - name: create mattermost/data foldder
    file: 
      path: /opt/mattermost/data
      state: directory

  - name: create the Mattermost group
    ansible.builtin.group:
      name: mattermost
      state: present
      system: yes
  
  - name: create the Mattermost user 
    ansible.builtin.user:
      name: mattermost
      groups: mattermost
      system: yes
  
  - name: give write permissions to the mattermost group
    ansible.builtin.file:
      path: /opt/mattermost
      owner: mattermost
      group: mattermost
      mode: g+w
      recurse: yes

  - name: set up the database driver in the file /opt/mattermost/config/config.json
    ansible.builtin.lineinfile:
      path: /opt/mattermost/config/config.json
      regexp: '"DataSource":'
      line: '    "DataSource": "postgres:/<mmuser:mmuser-password>@<host-name-or-IP>:5432/<databasename>?sslmode=disable&connect timeout=10",'

  - name: set up Mattermost to use systemd for starting and stopping.
    template:
      src: files/mattermost.service
      dest: /lib/systemd/system/
  
  - name: make systemd load the new unit.
    ansible.builtin.systemd:
      daemon_reload: yes
  
  - name: start the mattermost service.
    ansible.builtin.systemd:
      state: started
      name: mattermost.service
  
  - name: enable mattermost.service
    ansible.builtin.systemd:
      name: mattermost.service
      enabled: yes
      masked: no

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
 
  - name: replace the nginx.default file with mattermost file template
    template:
      src: files/mattermost
      dest: /etc/nginx/sites-available/

  - name: create symlink and enable the mattermost configuration
    file:
      src: /etc/nginx/sites-available/mattermost
      dest: /etc/nginx/sites-enabled/mattermost
      state: link

  - name: restart NGINX
    ansible.builtin.systemd:
      state: restarted
      name: nginx
    


 

  


