- name: get localhost's public ip address
  shell:
     cmd: "dig +short txt ch whoami.cloudflare @1.0.0.1"
  register: dig_localhost

- name: show ip
  debug:
     msg: '{{ dig_localhost.stdout[1:-1] }}'

- set_fact:
     public_ip: "{{ dig_localhost.stdout[1:-1] }}"



