- name: find or create key pair
  amazon.aws.ec2_key:
     name: "{{ name_prefix }}-mm-key-pair"
     force: false
     key_type: ed25519
     tags:
       Application: mattermost
       User: "{{ name_prefix }}"
  register: generated_key

