- name: find or create key pair
  amazon.aws.ec2_key:
     name: "{{ name_prefix }}-mm-key-pair"
     force: false
     key_type: ed25519
     tags:
       Application: mattermost
       User: "{{ name_prefix }}"
  register: generated_key

- name: make sure .pem has right permissions
  ansible.builtin.file:
     path: "mm-ansible-created-key.pem"
     state: touch
     mode: 0700

- name: create new .pem file
  copy:
     dest: "mm-ansible-created-key.pem"
     content: "{{ generated_key.key.private_key }}"
  when:
     generated_key.changed

