- name: find or create key pair
  amazon.aws.ec2_key:
     name: "kathrin-mm-key-pair"
     force: false
     key_type: ed25519
     tags:
       Application: mattermost
       User: kathrin
  register: generated_key

