- name: identify availability zones for current region
  amazon.aws.aws_az_info:
  register: az_info

- set_fact:
     chosen_az: "{{ az_info.availability_zones | random }}"

- name: find vpcs
  amazon.aws.ec2_vpc_net_info:
  register: vpc_info

- set_fact:
     vpc_id: "{{ vpc_info | community.general.json_query('vpcs[?is_default==`true`].vpc_id') | first }}"

- name: find subnets
  amazon.aws.ec2_vpc_subnet_info:
     filters:
        vpc-id: "{{ vpc_id }}"
        availability-zone: "{{ chosen_az.zone_name }}"
  register: subnet_info

- set_fact:
     chosen_subnet: "{{ subnet_info.subnets | first }}"

