- name: update apt cache and install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: create the Nginx user 
  ansible.builtin.user:
    name: nginx
    system: yes

- name: give permissions to nginx
  ansible.builtin.file:
    path: /var/cache/nginx/
    owner: nginx
    mode: g+w
    recurse: yes

- name: delete nginx.conf
  file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: replace with the new nginx.conf 
  template:
    src: roles/nginx/files/nginx.conf
    dest: /etc/nginx/

- name: delete default nginx site
  file:
    path: /etc/nginx/conf.d/default
    state: absent
        
- name: replace the nginx.default file with mattermost file template
  template:
    src: roles/nginx/files/mattermost
    dest: /etc/nginx/conf.d/

- name: create symlink and enable the mattermost configuration
  file:
    src: /etc/nginx/conf.d/mattermost
    dest: /etc/nginx/conf.d/default.conf
    state: link

- name: restart NGINX
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    