- name: install tools
  apt:
     pkg:
     - git
     - golang
     state: latest
     update_cache: true

- name: see if loadtest repo already exists
  stat:
     path: ./mattermost-load-test-ng
  register: gitrepo_exists

- name: print gitrepo check
  debug:
     msg: "{{ gitrepo_exists }}"

- name:  clone the loadtest repository
  shell:
     cmd: git clone https://github.com/mattermost/mattermost-load-test-ng
  when: gitrepo_exists.stat.exists == false

- name: copy config file
  copy:
     src: mattermost-load-test-ng/config/config.sample.json
     dest: mattermost-load-test-ng/config/config.json 
     mode: u=rw,g=r,o=r
     remote_src: yes

- name: adapt serverurl 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"ServerURL"'
     line: '     "ServerURL": "http://{{mm_private_ip}}:80",' 

- name: adapt websocketurl 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"WebSocketURL"'
     line: '     "WebSocketURL": "ws://{{mm_private_ip}}:80",' 

- name: adapt adminemail 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"AdminEmail"'
     line: '     "AdminEmail": "x@y.com",'

- name: adapt adminpwd 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"AdminPassword"'
     line: '     "AdminPassword": "{{ mm_admin_password }}"'

- name: copy simplecontroller file
  copy:
     src: mattermost-load-test-ng/config/simplecontroller.sample.json
     dest: mattermost-load-test-ng/config/simplecontroller.json 
     mode: u=rw,g=r,o=r
     remote_src: yes
