- name: install tools
  apt:
     pkg:
     - git
     - golang
     state: latest
     update_cache: true
  tags: loadtest

- name: see if loadtest repo already exists
  stat:
     path: ./mattermost-load-test-ng
  register: gitrepo_exists
  tags: loadtest

- name: print gitrepo check
  debug:
     msg: "{{ gitrepo_exists }}"
  tags: loadtest

- name:  clone the loadtest repository
  shell:
     cmd: git clone https://github.com/mattermost/mattermost-load-test-ng
  when: gitrepo_exists.stat.exists == false
  tags: loadtest

- name: copy config file
  copy:
     src: mattermost-load-test-ng/config/config.sample.json
     dest: mattermost-load-test-ng/config/config.json 
     mode: u=rw,g=r,o=r
     remote_src: yes
  tags: loadtest

- name: adapt serverurl 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"ServerURL"'
     line: '     "ServerURL": "http://{{mm_private_ip}}:80",' 
  tags: run_loadtest

- name: adapt websocketurl 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"WebSocketURL"'
     line: '     "WebSocketURL": "ws://{{mm_private_ip}}:80",' 
  tags: run_loadtest

- name: adapt adminemail 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"AdminEmail"'
     line: '     "AdminEmail": "x@y.com",'
  tags: run_loadtest

- name: adapt adminpwd 
  ansible.builtin.lineinfile:
     path: mattermost-load-test-ng/config/config.json
     regexp: '"AdminPassword"'
     line: '     "AdminPassword": "{{ mm_admin_password }}"'
  tags: run_loadtest

- name: copy simplecontroller file
  copy:
     src: mattermost-load-test-ng/config/simplecontroller.sample.json
     dest: mattermost-load-test-ng/config/simplecontroller.json 
     mode: u=rw,g=r,o=r
     remote_src: yes
  tags: loadtest

- name: create loadtest user
  ansible.builtin.user:
     create_home: yes
     name: loadtest
     state: present
     shell: /usr/bin/bash
  tags: loadtest

- name: change ownership of the loadtest files to ubuntu
  file:
     path: /home/ubuntu/mattermost-load-test-ng
     owner: ubuntu
     group: ubuntu
  tags: loadtest

