- name: create jenkins instance
  amazon.aws.ec2_instance:
    name: "{{ name_prefix }}-jenkins-instance"
    state: started
    exact_count: 1
    key_name: "{{ jenkins_key_pair }}"
    security_groups:
    -  "{{ name_prefix }}-mm-admin-group"
    filters:
      "tag:Name": "{{ name_prefix }}-jenkins-instance"
      "instance-state-name": "running"
    vpc_subnet_id : "{{ db_instance_subnet }}"
    instance_type: t2.micro
    instance_role: "{{ jenkins_iam_role }}"
    image_id: "{{ jenkins_ami }}"
    detailed_monitoring: yes
    tags:
       Application: mattermost
       User: "{{ name_prefix }}"
       Purpose: jenkins

