- name: install java
  yum:
     name: java
     state: present
     update_cache: yes
  tags: jenkins

- name: add the jenkins repository
  yum_repository:
        name: jenkins
        description: jenkins
        baseurl: "https://pkg.jenkins.io/redhat/"
        gpgkey: "https://pkg.jenkins.io/redhat/jenkins.io.key"
        gpgcheck: yes
  tags: jenkins

- name: install jenkins
  yum:
     name: jenkins
     state: present
     update_cache: yes
  tags: jenkins

- name: enable jenkins service
  service:
        name: jenkins
        state: started
        enabled: yes
  tags: jenkins
