- name: download cloudwatch agent
  shell:
     cmd: wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb && dpkg -i -E ./amazon-cloudwatch-agent.deb

     
- name: copy config file to instance
  template:
     src: files/config.json
     dest: /opt/aws/amazon-cloudwatch-agent/etc/config.json
  

- name: start cloudwatch agent
  shell:
     cmd: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json

- name: download prometheus
  shell:
     cmd: useradd --no-create-home prometheus && mkdir /etc/prometheus && mkdir /var/lib/prometheus && wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz && tar xzf prometheus-2.19.0.linux-amd64.tar.gz && cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin && cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin && cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus && cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus

- name: download prometheus exporter
  shell:
     cmd: wget https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz && tar -xzf nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz && mv nginx-prometheus-exporter /usr/local/bin  && useradd -r nginx_exporter

- name: copy the prometheus yaml file
  template:
     src: files/prometheus.yml
     dest: /etc/prometheus/prometheus.yml

- name: copy the prometheus service file
  template:
     src: files/prometheus.service
     dest: /etc/systemd/system/prometheus.service

- name: chown everything to prometheus owns it
  shell:
     cmd: chown prometheus:prometheus /etc/prometheus && chown prometheus:prometheus /usr/local/bin/prometheus && chown prometheus:prometheus /usr/local/bin/promtool && chown -R prometheus:prometheus /etc/prometheus/consoles && chown -R prometheus:prometheus /etc/prometheus/console_libraries &&  chown -R prometheus:prometheus /var/lib/prometheus

- name: copy the prometheus exporter service file
  template:
     src: files/nginx_prometheus_exporter.service
     dest: /etc/systemd/system/nginx_prometheus_exporter.service

- name: start the prometheus exporter service.
  ansible.builtin.systemd:
    state: started
    name: nginx_prometheus_exporter.service

- name: start the prometheus service
  ansible.builtin.systemd:
    state: started
    name: prometheus.service

