- name: download cloudwatch agent
  shell:
     cmd: wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb && dpkg -i -E ./amazon-cloudwatch-agent.deb

     
- name: copy config file to instance
  template:
     src: files/config.json
     dst: /opt/aws/amazon-cloudwatch-agent/config/config.json
  

- name: start cloudwatch agent
  shell:
     cmd: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json
