- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: replace the nginx.default file with mattermost file template
  template:
    src: files/mattermost
    dest: /etc/nginx/sites-available/

- name: create symlink and enable the mattermost configuration
  file:
    src: /etc/nginx/sites-available/mattermost
    dest: /etc/nginx/sites-enabled/mattermost
    state: link

- name: enable nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    masked: no

- name: restart NGINX
  ansible.builtin.systemd:
    state: restarted
    name: nginx
 
