global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'    
    static_configs:
      - targets: ['127.0.0.1:9113']
  - job_name: 'apache'
    static_configs:
      - targets: ['127.0.0.1:9117']
  - job_name: 'mattermost'
    static_configs:
      - targets: ['127.0.0.1:9093']
